package com.blueceylon.catalog_service.domain.model.enums;

public enum Region {
    HILL_COUNTRY, SOUTH_COAST, CULTURAL_TRIANGLE, EAST_COAST, WILDLIFE_BELT, WEST_COAST, NORTH,
    WESTERN_PROVINCE, SOUTHERN_PROVINCE, CENTRAL_PROVINCE, NORTHERN_PROVINCE, EASTERN_PROVINCE,
    NORTH_WESTERN_PROVINCE, NORTH_CENTRAL_PROVINCE, UVA_PROVINCE, SABARAGAMUWA_PROVINCE
}

